name: Nixtla Simplified Documentation (Preview)

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-preview-documentation:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    name: Clone all built documentation
    steps:
      - name: Clone nixtla
        uses: actions/checkout@v4
        with:
          repository: Nixtla/nixtla
          path: nixtla
          ref: docs-preview

      - name: Clone statsforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/statsforecast
          path: statsforecast
          ref: docs-preview

      - name: Clone mlforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/mlforecast
          path: mlforecast
          ref: docs-preview

      - name: Clone neuralforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/neuralforecast
          path: neuralforecast
          ref: docs-preview
      
      - name: Clone hierarchicalforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/hierarchicalforecast
          path: hierarchicalforecast
          ref: docs-preview

      - name: Clone utilsforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/utilsforecast
          path: utilsforecast
          ref: docs-preview

      - name: Clone datasetsforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/datasetsforecast
          path: datasetsforecast
          ref: docs-preview

      - name: Clone coreforecast
        uses: actions/checkout@v4
        with:
          repository: Nixtla/coreforecast
          path: coreforecast
          ref: docs-preview 
      
      - name: Copy documentation to the docs branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b docs-preview
          git add .
          git commit -m "Update documentation"
          git push origin docs-preview